//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterHost) DeepCopyInto(out *ExporterHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterHost.
func (in *ExporterHost) DeepCopy() *ExporterHost {
	if in == nil {
		return nil
	}
	out := new(ExporterHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExporterHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterHostList) DeepCopyInto(out *ExporterHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExporterHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterHostList.
func (in *ExporterHostList) DeepCopy() *ExporterHostList {
	if in == nil {
		return nil
	}
	out := new(ExporterHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExporterHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterHostSpec) DeepCopyInto(out *ExporterHostSpec) {
	*out = *in
	out.LocationRef = in.LocationRef
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Power = in.Power
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterHostSpec.
func (in *ExporterHostSpec) DeepCopy() *ExporterHostSpec {
	if in == nil {
		return nil
	}
	out := new(ExporterHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterHostStatus) DeepCopyInto(out *ExporterHostStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterHostStatus.
func (in *ExporterHostStatus) DeepCopy() *ExporterHostStatus {
	if in == nil {
		return nil
	}
	out := new(ExporterHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationRef) DeepCopyInto(out *LocationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationRef.
func (in *LocationRef) DeepCopy() *LocationRef {
	if in == nil {
		return nil
	}
	out := new(LocationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Power) DeepCopyInto(out *Power) {
	*out = *in
	out.SNMP = in.SNMP
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Power.
func (in *Power) DeepCopy() *Power {
	if in == nil {
		return nil
	}
	out := new(Power)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNMPPower) DeepCopyInto(out *SNMPPower) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNMPPower.
func (in *SNMPPower) DeepCopy() *SNMPPower {
	if in == nil {
		return nil
	}
	out := new(SNMPPower)
	in.DeepCopyInto(out)
	return out
}
